### ISSUE TITLE
[Question] About costume model and dataset

### ISSUE THREAD

**Issue by LostALice** [enriquetomasmb/nebula#3]
Hi, can you please tell me about how to upload or using costume model in this framework? I am not sure about modify/add code in core.model folder is correct or not.

**Comment by enriquetomasmb** [comment]
Hi @LostALice, the process to integrate new models is the following:

1. Create a directory with the name of your dataset in the "datasets" and "models" folders
2. In the first one, you must include a [dataset-name].py indicating how to obtain the data, processing techniques, etc.
3. In the second one, you have to define the model architecture to deal with the data
4. Include the new dataset/model option in deployment.html and the node.py files

Anyway, we are preparing a guide to help beginners with the process of platform extensibility. Any improvement you find interesting, don't hesitate to contact us or contribute directly to the repository.
