### ISSUE TITLE
custom topology

### ISSUE THREAD

**Issue by wenzhezhai** [enriquetomasmb/nebula#7]
Thank you for developing the platform.

I have a few questions about creating a specific type of topology and loading it into the dashboard while setting up a scenario. I checked the code and found it requires an n by n matrix, but I'm unsure how to load it.

Additionally, when the config file is generated, it includes both the matrix and neighbor attributes. Could you clarify if this is redundant or potentially conflicting? Shouldn't the topology already determine the connections between the nodes in the graph?

Thanks again.

**Comment by enriquetomasmb** [comment]
Hi @wenzhezhai, how is it going? Are you trying to design the topology using the dashboard or externally? The matrix is extracted from the interactive topology, and the node attributes are from the specific fields of the same page. Both elements are downloaded in the JSON file when you save the scenario, and it is necessary to restore all configurations when you load the file.
