### ISSUE TITLE
How to debug in docker

### ISSUE THREAD

**Issue by huyan2000** [enriquetomasmb/nebula#8]
When using it using docker, I found it doesn't output the logs per client, just wondering is there anyway that I can check real-time client output in info or debug level? 

Besides, I'm trying to implemet some new senarios but I'm having some code error, just wondering if you could suggest a way to do debugging, as it's running within docker, I'm unable to do pdb or ssh remote development with breakpoint.

**Comment by enriquetomasmb** [comment]
Hi @huyan2000, how are you doing? Regarding your first question, I suggest you download the main branch of the platform again and check if the issue persists. We made several changes in the last few months, and they may have solved your trouble.

In terms of debugging, I always recommend using the logger or traceback. Debugging the internal interactions between components in an asynchronous environment is quite hard. Feel free to share your scenario with us if you need more specific help.
